# Generated by Django 5.0.3 on 2024-04-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='User_Type',
            field=models.CharField(default='Manager', max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='Password',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
