# Generated by Django 5.0.3 on 2024-04-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
