# Generated by Django 5.0.3 on 2024-04-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_login_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='user_login_info',
        ),
    ]
